const {test}=require('node:test');
const assert=require('node:assert/strict');
const {inspect}=require('../diagnostics.js');
function image(w=160,h=100,low=0,high=255){const data=new Uint8ClampedArray(w*h*4);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const k=(y*w+x)*4,v=x>=30&&x<130&&y>=30&&y<70?((Math.floor(x/4)%2)?low:high):high;data[k]=data[k+1]=data[k+2]=v;data[k+3]=255;}return {data,width:w,height:h};}
const symbol={location:{points:[{x:30,y:30},{x:130,y:30},{x:130,y:70},{x:30,y:70}]},moduleSize:4,angle:0,decoded:true};
const find=(report,label)=>report.checks.find(x=>x.label===label);
test('no location yields unknown evidence, not a fabricated pass',()=>{const r=inspect(image(),null,0);assert.equal(r.checks.length,1);assert.equal(r.checks[0].level,'inconclusive');assert.ok(r.recommendations.length);});
test('high brightness range is a measurement, not a barcode quality pass',()=>{const r=inspect(image(),symbol,1);assert.equal(find(r,'Contrast').level,'measured');assert.match(find(r,'Contrast').note,/not a pass/);assert.equal(find(r,'Region size').level,'measured');assert.equal(find(r,'Rotation').level,'measured');assert.equal(find(r,'Quiet zone').level,'measured');assert.ok(!r.checks.some(c=>['Motion blur','Highlights','Inversion','Damage'].includes(c.label)));});
test('low contrast and undersampling produce actionable warnings',()=>{const r=inspect(image(160,100,110,140),{...symbol,moduleSize:1.3},1);assert.equal(find(r,'Contrast').level,'warn');assert.equal(find(r,'Module size').level,'warn');assert.equal(find(r,'Edge transitions').level,'inconclusive');assert.ok(r.recommendations.some(x=>x.includes('resolution')));});
test('missing module size stays unknown while pixel edges remain measurable',()=>{const r=inspect(image(),{...symbol,moduleSize:undefined},1);assert.match(find(r,'Module size').value,/Unknown/);assert.equal(find(r,'Module size').level,'inconclusive');assert.equal(find(r,'Edge transitions').level,'measured');});
test('cropped region warns without inventing a glare assessment',()=>{const r=inspect(image(),{...symbol,location:{points:[{x:0,y:30},{x:130,y:30},{x:130,y:70},{x:0,y:70}]}},1);assert.equal(find(r,'Partial crop').level,'warn');assert.equal(find(r,'Quiet zone').level,'warn');assert.equal(find(r,'Highlights'),undefined);});
test('perspective cue and neighboring candidates recommend appropriate fixes',()=>{const r=inspect(image(),{...symbol,decoded:false,location:{points:[{x:30,y:30},{x:130,y:30},{x:100,y:70},{x:50,y:70}]}},3);assert.equal(find(r,'Perspective').level,'warn');assert.equal(find(r,'Neighbors').level,'warn');assert.ok(r.recommendations.some(x=>x.includes('Parameter Tuner')));});
const manual={location:symbol.location,manual:true,decoded:false};
test('manual selection shows calculated image evidence, not symbol placeholders',()=>{const r=inspect(image(160,100,110,140),manual,null);assert.equal(find(r,'Contrast').level,'warn');for(const name of ['Rotation','Perspective','Quiet zone','Module size','Neighbors','Motion blur','Highlights','Inversion','Damage'])assert.equal(find(r,name),undefined);assert.ok(r.findings.some(f=>f.label==='Contrast'&&f.impact.includes('localization')&&f.action));});
test('broad image transitions flag softness without needing SDK module size',()=>{const im=image();for(let y=0;y<im.height;y++)for(let x=0;x<im.width;x++){const t=x%32;const v=t<8?255:t<16?255-(t-8)*255/8:t<24?0:(t-24)*255/8;const i=(y*im.width+x)*4;im.data[i]=im.data[i+1]=im.data[i+2]=v;}const r=inspect(im,manual,null);assert.equal(find(r,'Edge transitions').level,'warn');assert.ok(r.findings.some(f=>f.label==='Edge transitions'&&f.impact.includes('gradual shading')));});
test('dark capture and clipped selection yield pixel evidence with advice',()=>{const r=inspect(image(160,100,10,50),{...manual,location:{points:[{x:0,y:0},{x:130,y:0},{x:130,y:70},{x:0,y:70}]}},null);assert.equal(find(r,'Dark capture').level,'warn');assert.equal(find(r,'Partial crop').level,'warn');assert.ok(r.findings.every(f=>f.evidence&&f.action&&f.impact));});
