/*
 * Boarding Pass Scanner
 *
 * Dynamsoft Barcode Reader decodes the symbol; the IATA BCBP payload is parsed
 * by bcbp.js, a standalone Resolution 792 parser.
 *
 * Structure note: everything below is shared with the copy deployed under
 * dynamsoft.com/codepool/demos/. The ONLY difference between the two is the
 * "License" section — this example asks the visitor for a key, the hosted copy
 * resolves one from the hostname. Keeping that to one function means the two
 * files can be diffed by eye.
 */
(function () {
  'use strict';

  /* =========================================================================
     License

     Self-hosted deployments need their own Dynamsoft license. Paste your key,
     or press "Use Trial License" for the SDK's public 24-hour key.
     ========================================================================= */

  var TRIAL_LICENSE_KEY = 'DLS2eyJoYW5kc2hha2VDb2RlIjoiMjAwMDAxLTE2NDk4Mjk3OTI2MzUiLCJvcmdhbml6YXRpb25JRCI6IjIwMDAwMSIsInNlc3Npb25QYXNzd29yZCI6IndTcGR6Vm05WDJrcEQ5YUoifQ==';

  /* Replaced in the hosted copy, which has no setup screen and activates
     immediately. Returning a resolved key keeps bootstrap() identical. */
  function acquireLicense() {
    return new Promise(function (resolve) {
      var screen = document.getElementById('license-setup');
      var input = document.getElementById('license-key');
      var submit = document.getElementById('license-submit');
      var trial = document.getElementById('use-trial');

      licenseUi.setBusy = function (busy) {
        submit.disabled = busy;
        trial.disabled = busy;
        submit.textContent = busy ? 'Initializing…' : 'Initialize Scanner';
      };
      licenseUi.hide = function () {
        screen.style.display = 'none';
        document.getElementById('scanner-app').classList.remove('hidden');
      };

      submit.addEventListener('click', function () {
        var key = input.value.trim();
        if (!key) {
          alert('Please enter a license key');
          return;
        }
        resolve(key);
      });

      trial.addEventListener('click', function () { resolve(TRIAL_LICENSE_KEY); });

      input.addEventListener('keydown', function (event) {
        if (event.key === 'Enter' && (event.ctrlKey || event.metaKey)) submit.click();
      });
    });
  }

  /* No-ops until acquireLicense() fills them in. The hosted copy leaves them
     empty because it has neither a setup screen nor a submit button. */
  var licenseUi = { setBusy: function () { }, hide: function () { } };

  /* =========================================================================
     Configuration
     ========================================================================= */

  /* A boarding pass carries a 2D symbol: PDF417 (and the compact MicroPDF417)
     on printed passes, and PDF417, Aztec, QR Code or Data Matrix on mobile and
     2D printed passes from BCBP version 7 onwards.

     These names come from Dynamsoft.DBR.EnumBarcodeFormat. Note that the Aztec
     entry is BF_AZTEC, not BF_AZTEC_CODE. Any name this SDK build does not
     define is reported to the console rather than silently ignored. */
  var BOARDING_FORMATS = [
    'BF_PDF417', 'BF_MICRO_PDF417', 'BF_AZTEC', 'BF_QR_CODE', 'BF_DATAMATRIX', 'BF_MICRO_QR'
  ];
  var ALL_2D_FORMATS = BOARDING_FORMATS.concat(['BF_MAXICODE', 'BF_DOTCODE']);

  var PRESET_TEMPLATE = 'ReadBarcodes_Balance';
  var MAX_IMAGE_WIDTH = 4000;

  /* Generated by the companion boarding pass generator, so every sample has a
     known payload: see sample-images/README.md for the expected fields. */
  var SAMPLE_IMAGES = [
    { file: 'printed-pdf417.png', label: 'Printed pass — PDF417' },
    { file: 'mobile-pdf417.png', label: 'Mobile pass — PDF417' },
    { file: 'two-leg-pdf417.png', label: 'Two-leg pass' },
    { file: 'barcode-pdf417.png', label: 'PDF417 symbol' },
    { file: 'barcode-qrcode.png', label: 'QR Code symbol' },
    { file: 'barcode-datamatrix.png', label: 'Data Matrix symbol' },
    { file: 'barcode-azteccode.png', label: 'Aztec Code symbol' }
  ];

  /* =========================================================================
     State
     ========================================================================= */

  var els = {};
  var state = {
    mode: 'camera',
    scope: 'boarding',
    sdkReady: false,
    resultsOpen: false,
    configuredScope: null,
    lastResult: null
  };

  var cameraView = null;
  var cameraEnhancer = null;
  var cvRouter = null;
  var receiver = null;

  /* =========================================================================
     Bootstrap
     ========================================================================= */

  function bootstrap() {
    cacheElements();
    wireEvents();
    buildSamples();
    updateModeUI();

    acquireLicense().then(function (licenseKey) {
      licenseUi.setBusy(true);
      return initSDK(licenseKey).then(function () {
        licenseUi.hide();
        return startCameraMode().catch(function (cameraError) {
          /* No camera, permission denied, or the device is still being released.
             Upload mode needs no camera, so fall back rather than stranding the
             visitor on an empty page. */
          console.error('Camera unavailable, falling back to Upload mode:', cameraError);
          return startUploadMode();
        });
      }, function (error) {
        /* initSDK failed, which almost always means the key is wrong or is
           bound to a different domain. */
        console.error(error);
        licenseUi.setBusy(false);
        alert('Dynamsoft could not activate with that license:\n\n'
          + ((error && error.message) || error)
          + '\n\nCheck the key, and that it is allowed for this domain, then try again.');
      });
    });
  }

  function cacheElements() {
    els.tip = document.getElementById('tip-message');
    els.cameraView = document.getElementById('camera-view');
    els.mainContainer = document.getElementById('main-container');
    els.modeSwitch = document.getElementById('mode-switch-container');
    els.uploadZone = document.getElementById('upload-zone');
    els.uploadInput = document.getElementById('upload-input');
    els.results = document.getElementById('results');
    els.resultsContent = document.getElementById('results-content');
    els.resultsTitle = document.getElementById('results-title');
    els.scopeSelect = document.getElementById('scope-select');
    els.sampleRow = document.getElementById('sample-row');
  }

  function initSDK(licenseKey) {
    /* The license must be activated before any component is created, otherwise
       CaptureVisionRouter.createInstance() throws. */
    return Dynamsoft.License.LicenseManager.initLicense(licenseKey, true)
      .then(function () {
        /* The barcode module is all this page needs: it decodes the symbol, and
           the IATA BCBP layout is then read by bcbp.js. */
        return Dynamsoft.Core.CoreModule.loadWasm(['DBR']);
      })
      .then(function () {
        return Dynamsoft.DCE.CameraView.createInstance();
      })
      .then(function (view) {
        cameraView = view;
        return Dynamsoft.DCE.CameraEnhancer.createInstance(cameraView);
      })
      .then(function (enhancer) {
        cameraEnhancer = enhancer;
        return Dynamsoft.CVR.CaptureVisionRouter.createInstance();
      })
      .then(function (router) {
        cvRouter = router;

        /* Consecutive frames see the same symbol; without deduplication the
           results panel would re-open dozens of times a second. */
        var filter = new Dynamsoft.Utility.MultiFrameResultCrossFilter();
        filter.enableResultDeduplication('barcode', true);
        return cvRouter.addResultFilter(filter);
      })
      .then(function () {
        els.cameraView.replaceChildren(cameraView.getUIElement());
        receiver = {
          onDecodedBarcodesReceived: function (result) {
            if (state.resultsOpen || state.mode !== 'camera') return;
            var items = (result && result.barcodeResultItems) || [];
            if (items.length) showResults(items, currentCameraFrame());
          }
        };
        state.sdkReady = true;
        return applySettings(true);
      });
  }

  /* =========================================================================
     Formats
     ========================================================================= */

  function formatEnum() {
    return (window.Dynamsoft && Dynamsoft.DBR && Dynamsoft.DBR.EnumBarcodeFormat) || null;
  }

  /* The format mask spans more than 32 bits, so this SDK build exposes the enum
     values as BigInt. A plain `var mask = 0` throws "Cannot mix BigInt and other
     types" on the first `|=`, which is why the accumulator starts at 0n. */
  function scopeMask() {
    var table = formatEnum();
    if (!table) return null;

    if (state.scope === 'all') return table.BF_ALL === undefined ? null : table.BF_ALL;

    var names = state.scope === 'boarding' ? BOARDING_FORMATS : ALL_2D_FORMATS;
    var mask = 0n;
    var missing = [];
    names.forEach(function (name) {
      if (table[name] === undefined) {
        missing.push(name);
        return;
      }
      mask |= table[name];
    });
    if (missing.length) console.warn('Barcode formats missing from this SDK build:', missing);
    return mask || null;
  }

  function applySettings(force) {
    if (!state.sdkReady && !force) return Promise.resolve();
    if (!cvRouter) return Promise.resolve();
    if (!force && state.configuredScope === state.scope) return Promise.resolve();

    return cvRouter.getSimplifiedSettings(PRESET_TEMPLATE).then(function (settings) {
      var mask;
      try {
        mask = scopeMask();
      } catch (error) {
        /* Narrowing the symbologies is an optimisation, not a requirement. If
           the mask cannot be built, scan with the preset's own default rather
           than failing to start. */
        console.warn('Could not build the format mask; using the preset default:', error);
        mask = null;
      }
      if (mask !== null) settings.barcodeSettings.barcodeFormatIds = mask;
      return cvRouter.updateSettings(PRESET_TEMPLATE, settings);
    }).then(function () {
      state.configuredScope = state.scope;
    });
  }

  /* =========================================================================
     Modes
     ========================================================================= */

  function startCameraMode() {
    state.mode = 'camera';
    updateModeUI();
    els.mainContainer.hidden = false;
    els.uploadZone.hidden = true;

    cvRouter.removeResultReceiver(receiver);
    /* stopCapturing() and close() are not guaranteed to hand back a promise, so
       each result is wrapped rather than chained onto directly. */
    return Promise.resolve(cvRouter.stopCapturing()).then(function () {
      return cameraEnhancer.isOpen() ? Promise.resolve(cameraEnhancer.close()) : undefined;
    }).then(function () {
      /* singleFrameMode has to change while the camera is closed. */
      cameraEnhancer.singleFrameMode = 'disabled';
      return openCamera();
    }).then(function () {
      cvRouter.setInput(cameraEnhancer);
      return applySettings();
    }).then(function () {
      return Promise.resolve(cvRouter.startCapturing(PRESET_TEMPLATE));
    }).then(function () {
      cvRouter.addResultReceiver(receiver);
      showTip('Point the camera at the barcode on a boarding pass.');
    });
  }

  function startUploadMode() {
    state.mode = 'upload';
    updateModeUI();
    els.mainContainer.hidden = true;
    els.uploadZone.hidden = false;

    cvRouter.removeResultReceiver(receiver);
    return Promise.resolve(cvRouter.stopCapturing()).then(function () {
      return cameraEnhancer.isOpen() ? Promise.resolve(cameraEnhancer.close()) : undefined;
    }).then(function () {
      showTip('Load an image of a boarding pass barcode.');
    });
  }

  /* Open the camera, retrying once. Right after a mode switch the previous
     session may still be releasing the device and the SDK then rejects with
     "Error opening camera: Camera closed." */
  function openCamera() {
    return Promise.resolve(cameraEnhancer.open()).catch(function (error) {
      console.warn('Camera open failed, retrying once:', error);
      return delay(400).then(function () { return cameraEnhancer.open(); });
    });
  }

  function delay(ms) {
    return new Promise(function (resolve) { setTimeout(resolve, ms); });
  }

  function switchMode(mode) {
    if (state.mode === mode || !state.sdkReady) return;
    var start = mode === 'camera' ? startCameraMode : startUploadMode;
    Promise.resolve(start()).catch(function (error) {
      console.error(error);
      showTip(mode === 'camera'
        ? 'Could not start the camera. Switch to Upload mode instead.'
        : 'Could not switch to Upload mode. Please refresh the page and try again.', true);
    });
  }

  function updateModeUI() {
    Array.prototype.forEach.call(document.querySelectorAll('.mode-option'), function (option) {
      option.classList.toggle('active', option.getAttribute('data-mode') === state.mode);
    });
    els.modeSwitch.setAttribute('data-active', state.mode);
  }

  function showTip(message, isError) {
    els.tip.textContent = message;
    els.tip.classList.toggle('is-error', !!isError);
  }

  /* =========================================================================
     Decoding
     ========================================================================= */

  function imageToDsImageData(img) {
    var width = img.naturalWidth || img.width;
    var height = img.naturalHeight || img.height;
    if (width > MAX_IMAGE_WIDTH) {
      height = Math.round(height * MAX_IMAGE_WIDTH / width);
      width = MAX_IMAGE_WIDTH;
    }

    var canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = height;
    var ctx = canvas.getContext('2d', { willReadFrequently: true });
    /* Composite onto white before drawing. A PNG may carry an alpha channel —
       anything exported from a canvas usually does — and a transparent pixel
       drawn onto a blank canvas stays (0,0,0,0). Passed to the SDK as RGBA that
       reads as black, so the quiet zone becomes ink and the symbol disappears. */
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, width, height);
    ctx.drawImage(img, 0, 0, width, height);

    var pixels = ctx.getImageData(0, 0, width, height);
    /* This is exactly the shape CaptureVisionRouter.capture() expects: an RGBA
       buffer straight out of getImageData(), stride 4 x width, format 10
       (IPF_ABGR_8888). A Blob or canvas takes a different internal path and
       silently returns no results. */
    return {
      bytes: new Uint8Array(pixels.data.buffer, pixels.data.byteOffset, pixels.data.length),
      width: width,
      height: height,
      stride: 4 * width,
      format: 10
    };
  }

  function loadImageElement(src) {
    return new Promise(function (resolve, reject) {
      var img = new Image();
      img.onload = function () { resolve(img); };
      img.onerror = function () { reject(new Error('The image could not be decoded.')); };
      img.src = src;
    });
  }

  function barcodeItemsFrom(result) {
    if (!result) return [];
    if (result.barcodeResultItems && result.barcodeResultItems.length) return result.barcodeResultItems;
    return (result.items || []).filter(function (item) {
      return item.type === Dynamsoft.Core.EnumCapturedResultItemType.CRIT_BARCODE;
    });
  }

  function decodeImage(src) {
    return loadImageElement(src).then(function (img) {
      return applySettings().then(function () {
        return cvRouter.capture(imageToDsImageData(img), PRESET_TEMPLATE);
      });
    }).then(barcodeItemsFrom);
  }

  function scanImageSource(src) {
    if (!state.sdkReady) {
      showTip('The scanner is still starting. Try again in a moment.', true);
      return;
    }
    showTip('Reading the image…');
    return decodeImage(src).then(function (items) {
      if (!items.length) {
        showTip('No barcode was found in that image. Try a larger or sharper crop of the barcode.', true);
        return;
      }
      showResults(items, src);
    }).catch(function (error) {
      console.error(error);
      showTip('That image could not be read: ' + ((error && error.message) || error), true);
    });
  }

  function handleImageFile(file) {
    if (!file) return;
    if (!/^image\//.test(file.type)) {
      showTip('That file is not an image. Upload a PNG, JPG, BMP or WebP picture of a boarding pass barcode.', true);
      return;
    }
    readAsDataURL(file).then(scanImageSource).catch(function (error) {
      console.error(error);
      showTip('That file could not be read.', true);
    });
  }

  function readAsDataURL(file) {
    return new Promise(function (resolve, reject) {
      var reader = new FileReader();
      reader.onload = function (event) { resolve(event.target.result); };
      reader.onerror = function () { reject(new Error('The file could not be read.')); };
      reader.readAsDataURL(file);
    });
  }

  function imageFromClipboard(event) {
    var data = event.clipboardData || window.clipboardData;
    if (!data) return null;
    if (data.files && data.files.length) {
      for (var i = 0; i < data.files.length; i++) {
        if (/^image\//.test(data.files[i].type)) return data.files[i];
      }
    }
    if (data.items) {
      for (var j = 0; j < data.items.length; j++) {
        if (/^image\//.test(data.items[j].type)) {
          var file = data.items[j].getAsFile();
          if (file) return file;
        }
      }
    }
    return null;
  }

  /* =========================================================================
     Results
     ========================================================================= */

  function showResults(items, imageSrc) {
    var payload = String(items[0].text || '');
    var format = formatName(items[0].formatString || items[0].format);

    if (!payload) {
      els.resultsTitle.textContent = 'Barcode read, but it carried no text';
      els.resultsContent.replaceChildren(notice('The symbol decoded as ' + format
        + ', but the SDK returned no text for it. This usually means the symbol uses a'
        + ' binary or otherwise unsupported encoding.'));
      openResults();
      return;
    }

    var decoded = window.Bcbp.decode(payload);
    state.lastResult = { payload: payload, format: format, decoded: decoded };

    els.resultsTitle.textContent = decoded.ok
      ? decoded.passengerName + ' \u00b7 ' + decoded.route
      : 'Not a BCBP boarding pass';

    var frag = document.createDocumentFragment();
    /* The image the barcode was read from, so the parse can be checked against
       what the camera or the file actually showed. */
    if (imageSrc) {
      frag.appendChild(scannedImage(imageSrc, format, payload.length));
    }
    if (decoded.ok) {
      frag.appendChild(passCard(decoded));
      frag.appendChild(section('Structural checks', checkList(decoded)));
      frag.appendChild(section('All fields in the payload', fieldTable(decoded)));
      if (decoded.warnings.length) {
        frag.appendChild(notice('Warnings: ' + decoded.warnings.join(' '), 'warn'));
      }
    } else {
      frag.appendChild(notice(decoded.error + ' The barcode was read as ' + format
        + ', so it decoded correctly — it simply is not an IATA BCBP payload.', 'warn'));
    }

    frag.appendChild(section('Decoded barcode content', rawBlock(payload, format)));
    els.resultsContent.replaceChildren(frag);
    showTip(decoded.ok
      ? 'Boarding pass read \u2014 ' + decoded.passengerName + ', ' + decoded.route + '.'
      : 'Barcode read, but it is not a BCBP boarding pass.');
    openResults();
  }

  /* The image section. Shown for a file, a drop, a paste or a sample; camera
     frames are snapshotted from the viewfinder so that path has one too. */
  function scannedImage(src, format, payloadLength) {
    var box = el('section', 'result-section');
    box.appendChild(el('h3', null, 'Scanned image'));

    var figure = el('figure', 'scan-figure');
    var img = el('img', 'scan-image');
    img.src = src;
    img.alt = 'The image the barcode was decoded from';
    img.loading = 'lazy';
    figure.appendChild(img);

    var caption = el('figcaption');
    caption.appendChild(el('span', 'scan-meta', format + ' \u00b7 ' + payloadLength + ' characters'));

    var toggle = el('button', 'link-button', 'View full size');
    toggle.type = 'button';
    toggle.setAttribute('aria-expanded', 'false');
    function setZoom(zoomed) {
      figure.classList.toggle('is-zoomed', zoomed);
      toggle.textContent = zoomed ? 'Fit to width' : 'View full size';
      toggle.setAttribute('aria-expanded', zoomed ? 'true' : 'false');
    }
    toggle.addEventListener('click', function () {
      setZoom(!figure.classList.contains('is-zoomed'));
    });
    /* Clicking the picture itself is the obvious gesture, so it does the same. */
    img.addEventListener('click', function () {
      setZoom(!figure.classList.contains('is-zoomed'));
    });

    caption.appendChild(toggle);
    figure.appendChild(caption);
    box.appendChild(figure);
    return box;
  }

  /* A still of what the viewfinder is showing, so camera results carry an image
     too. getUserMedia frames are same-origin, so the canvas stays readable. */
  function currentCameraFrame() {
    var video = document.querySelector('#camera-view video');
    if (!video || !video.videoWidth) return null;
    try {
      var canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      return canvas.toDataURL('image/jpeg', 0.85);
    } catch (error) {
      console.warn('Could not snapshot the camera frame:', error);
      return null;
    }
  }

  function formatName(value) {
    var text = String(value === undefined || value === null ? '' : value);
    var match = /^BF_(.+)$/.exec(text);
    if (!match) return text || 'unknown';
    return match[1].toLowerCase().replace(/_/g, ' ').replace(/\b(.)/g, function (m) {
      return m.toUpperCase();
    });
  }

  function el(tag, className, textContent) {
    var node = document.createElement(tag);
    if (className) node.className = className;
    if (textContent !== undefined) node.textContent = textContent;
    return node;
  }

  function notice(message, kind) {
    return el('div', 'note ' + (kind || 'info'), message);
  }

  function section(title, content) {
    var box = el('section', 'result-section');
    box.appendChild(el('h3', null, title));
    box.appendChild(content);
    return box;
  }

  /* The visual summary: what the pass says, arranged the way a pass is. */
  function passCard(decoded) {
    var card = el('div', 'pass-card');

    var head = el('div', 'pass-head');
    head.appendChild(el('span', 'pass-airline', decoded.carrierName || decoded.carrier));
    head.appendChild(el('span', 'pass-class', decoded.legs[0].compartmentLabel || ''));
    card.appendChild(head);

    var route = el('div', 'pass-route');
    route.appendChild(routeEnd(decoded.legs[0].from, decoded.legs[0].fromCity));
    route.appendChild(el('span', 'pass-arrow', '\u2192'));
    route.appendChild(routeEnd(decoded.legs[0].to, decoded.legs[0].toCity));
    card.appendChild(route);

    var facts = el('div', 'pass-facts');
    [
      ['Passenger', decoded.passengerName],
      ['PNR', decoded.pnr],
      ['Flight', decoded.carrier + ' ' + decoded.flightNumber],
      ['Date', decoded.legs[0].flightDateLabel || decoded.legs[0].julianDate],
      ['Seat', decoded.legs[0].seat || 'unassigned'],
      ['Sequence', decoded.sequence],
      ['Status', decoded.passengerStatus
        + (decoded.passengerStatusLabel ? ' \u00b7 ' + decoded.passengerStatusLabel : '')],
      ['Symbology', 'BCBP ' + (decoded.version === null ? 'v0 (no version field)' : 'v' + decoded.version)]
    ].forEach(function (pair) {
      var fact = el('div', 'pass-fact');
      fact.appendChild(el('span', 'pass-fact-label', pair[0]));
      fact.appendChild(el('span', 'pass-fact-value', pair[1]));
      facts.appendChild(fact);
    });
    card.appendChild(facts);

    if (decoded.legs.length > 1) {
      var list = el('div', 'pass-legs');
      decoded.legs.forEach(function (leg) {
        list.appendChild(el('div', 'pass-leg', 'Leg ' + leg.index + '  \u00b7  ' + leg.from + ' \u2192 ' + leg.to
          + '  \u00b7  ' + leg.carrier + ' ' + leg.flightNumber + '  \u00b7  '
          + (leg.flightDateLabel || leg.julianDate) + '  \u00b7  seat ' + (leg.seat || 'unassigned')));
      });
      card.appendChild(list);
    }

    return card;
  }

  function routeEnd(code, city) {
    var box = el('span', 'pass-end');
    box.appendChild(el('span', 'pass-code', code));
    box.appendChild(el('span', 'pass-city', city || ''));
    return box;
  }

  function checkList(decoded) {
    var list = el('div', 'check-list');
    decoded.checks.forEach(function (check) {
      var row = el('div', 'check-row ' + (check.ok ? 'check-ok' : 'check-bad'));
      row.appendChild(el('span', 'check-mark', check.ok ? '\u2713' : '\u2717'));
      row.appendChild(el('span', 'check-label', check.label));
      row.appendChild(el('span', 'check-detail', check.detail));
      list.appendChild(row);
    });
    return list;
  }

  function fieldTable(decoded) {
    var wrap = el('div', 'field-table');
    var head = el('div', 'field-row field-head');
    ['Item', 'Field', 'Value', 'Meaning'].forEach(function (name) {
      head.appendChild(el('span', null, name));
    });
    wrap.appendChild(head);

    if (decoded.unique.length) {
      wrap.appendChild(groupRow('Optional data \u2014 once per pass'));
      decoded.unique.forEach(function (field) {
        if (field.value) wrap.appendChild(fieldRow(field));
      });
    }

    decoded.legs.forEach(function (leg) {
      wrap.appendChild(groupRow(decoded.legs.length > 1
        ? 'Leg ' + leg.index + ' \u2014 ' + leg.from + ' \u2192 ' + leg.to
        : 'Flight data'));
      leg.fields.forEach(function (field) {
        if (field.value) wrap.appendChild(fieldRow(field));
      });
    });

    if (decoded.security) {
      wrap.appendChild(groupRow('Security section'));
      var row = el('div', 'field-row');
      row.appendChild(el('span', 'field-item', '25\u201330'));
      row.appendChild(el('span', null, 'Security data'));
      row.appendChild(el('span', 'field-value', decoded.security.data));
      row.appendChild(el('span', 'field-meaning',
        'Type ' + decoded.security.type + ', ' + decoded.security.size + ' bytes'));
      wrap.appendChild(row);
    }

    return wrap;
  }

  function groupRow(title) {
    var row = el('div', 'field-group-row');
    row.appendChild(el('span', null, title));
    return row;
  }

  function fieldRow(field) {
    var row = el('div', 'field-row');
    row.appendChild(el('span', 'field-item', String(field.item)));
    row.appendChild(el('span', null, field.label));
    row.appendChild(el('span', 'field-value', field.value));
    row.appendChild(el('span', 'field-meaning', field.meaning || ''));
    return row;
  }

  function rawBlock(payload, format) {
    var box = el('div', 'raw-block');
    box.appendChild(el('div', 'raw-meta', payload.length + ' characters \u00b7 ' + format));
    box.appendChild(el('pre', 'raw-payload', payload));
    return box;
  }

  function openResults() {
    state.resultsOpen = true;
    els.results.classList.add('is-open');
    els.results.scrollTop = 0;
  }

  function closeResults() {
    state.resultsOpen = false;
    els.results.classList.remove('is-open');
  }

  /* A flat JSON view of the parse, which is what most callers actually want to
     pipe into the rest of their application. */
  function toJson(decoded) {
    return {
      format: 'BCBP',
      version: decoded.version,
      passenger: {
        name: decoded.passengerName,
        surname: decoded.surname,
        givenNames: decoded.givenNames,
        pnr: decoded.pnr,
        status: decoded.passengerStatus,
        statusLabel: decoded.passengerStatusLabel,
        electronicTicket: decoded.electronicTicket
      },
      legs: decoded.legs.map(function (leg) {
        return {
          index: leg.index,
          from: leg.from,
          fromCity: leg.fromCity,
          to: leg.to,
          toCity: leg.toCity,
          carrier: leg.carrier,
          carrierName: leg.carrierName,
          flightNumber: leg.flightNumber,
          julianDate: leg.julianDate,
          flightDate: leg.flightDate,
          compartment: leg.compartment,
          compartmentLabel: leg.compartmentLabel,
          seat: leg.seat,
          sequence: leg.sequence,
          pnr: leg.pnr
        };
      }),
      optional: decoded.unique.concat(decoded.legs.reduce(function (acc, leg) {
        return acc.concat(leg.fields);
      }, [])).filter(function (field) {
        return field.value !== '';
      }).map(function (field) {
        return {
          item: field.item,
          code: field.code,
          label: field.label,
          value: field.value,
          meaning: field.meaning || undefined,
          offset: field.offset + 1
        };
      }),
      security: decoded.security || undefined,
      checks: decoded.checks,
      warnings: decoded.warnings,
      payload: decoded.raw
    };
  }

  /* =========================================================================
     Samples and wiring
     ========================================================================= */

  function buildSamples() {
    SAMPLE_IMAGES.forEach(function (sample) {
      var chip = el('button', 'sample-chip', sample.label);
      chip.type = 'button';
      chip.addEventListener('click', function (event) {
        /* The chips sit inside the drop zone, whose own click handler opens the
           file picker. Without this the chip would do both. */
        event.stopPropagation();
        scanImageSource('./sample-images/' + sample.file);
      });
      els.sampleRow.appendChild(chip);
    });
  }

  function wireEvents() {
    document.querySelector('#results .close-button').addEventListener('click', closeResults);

    Array.prototype.forEach.call(document.querySelectorAll('.mode-option'), function (option) {
      option.addEventListener('click', function (event) {
        switchMode(event.currentTarget.getAttribute('data-mode'));
      });
    });

    els.scopeSelect.addEventListener('change', function () {
      state.scope = els.scopeSelect.value;
      applySettings().then(function () {
        showTip(state.scope === 'boarding'
          ? 'Looking for boarding pass symbologies: PDF417, Aztec, QR Code and Data Matrix.'
          : 'Looking for a wider set of 2D formats.');
      });
    });

    els.uploadZone.addEventListener('click', function () { els.uploadInput.click(); });
    els.uploadZone.addEventListener('keydown', function (event) {
      if (event.key === 'Enter' || event.key === ' ') {
        event.preventDefault();
        els.uploadInput.click();
      }
    });

    els.uploadInput.addEventListener('change', function () {
      if (this.files && this.files.length) handleImageFile(this.files[0]);
      this.value = '';
    });

    ['dragenter', 'dragover'].forEach(function (type) {
      els.uploadZone.addEventListener(type, function (event) {
        event.preventDefault();
        els.uploadZone.classList.add('dragover');
      });
    });
    ['dragleave', 'drop'].forEach(function (type) {
      els.uploadZone.addEventListener(type, function (event) {
        event.preventDefault();
        els.uploadZone.classList.remove('dragover');
      });
    });
    els.uploadZone.addEventListener('drop', function (event) {
      var files = event.dataTransfer && event.dataTransfer.files;
      if (files && files.length) handleImageFile(files[0]);
    });

    document.addEventListener('paste', function (event) {
      if (state.mode !== 'upload') return;
      var file = imageFromClipboard(event);
      if (!file) return;
      event.preventDefault();
      handleImageFile(file);
    });

    var copyButton = document.getElementById('copy-all-button');
    copyButton.addEventListener('click', function () {
      if (!state.lastResult) return;
      var text = state.lastResult.decoded.ok
        ? JSON.stringify(toJson(state.lastResult.decoded), null, 2)
        : state.lastResult.payload;
      navigator.clipboard.writeText(text).then(function () {
        copyButton.textContent = 'Copied';
        setTimeout(function () { copyButton.textContent = 'Copy JSON'; }, 1400);
      });
    });

    window.addEventListener('resize', handleViewportChange);
    window.addEventListener('orientationchange', handleViewportChange);
  }

  function handleViewportChange() {
    if (cameraEnhancer && typeof cameraEnhancer.resize === 'function') {
      try {
        cameraEnhancer.resize();
      } catch (error) {
        /* the enhancer is not open yet */
      }
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', bootstrap);
  } else {
    bootstrap();
  }
})();
